### ISSUE TITLE
Баг при выборе целей для атаки

### ISSUE THREAD

**Issue by cyrilshishkin** [basiliscos/lua-polkovodets#3]
Компьютер по-прежнему очень неправильно выбирает то Оружие, которое атакуется

**Comment by basiliscos** [comment]
а пример?

**Comment by cyrilshishkin** [comment]
так на словах уже все проговорили

**Comment by basiliscos** [comment]
Точно. Только правильно описать так: рандомная стрельба ведётся по оружиям, а не по единицам оружия, что ведёт к неествестенным потерям - одних вышибает полностью, а других совсем не трогает.

Исправлю.

**Comment by basiliscos** [comment]
вроде исправлено
