### ISSUE TITLE
динамический бонус GRANTS_DEF_ATTACK для пехоты инициирующего

### ISSUE THREAD

**Issue by basiliscos** [basiliscos/lua-polkovodets#4]
1. имеется оружие (= танки, бтры) с флагом `GRANTS_DEF_ATTACK` и сборным значением `Q/D`, обозначающим что каждая единица оружия с данным флагом придаёт дополнительный бонус `D` `Q` единицам пехоты (`wc_infant`), выбранных случайным образом

2. бонус (пере)считывается каждый раз перед проигрыванием очередного блока, т.е. если в предыдущем блоке танк уничтожили, в текущем блоке от него бонуса не будет.

**Comment by cyrilshishkin** [comment]
Есть один сложный момент. Когда у нас идет КОНТРАТАКА или ВСТРЕЧНЫЙ БОЙ то защита должна быть у пехоты обоих Юнитов

**Comment by basiliscos** [comment]
это другая фича, которую надо делать отдельно и после этой

**Comment by basiliscos** [comment]
done
