### ISSUE TITLE
Учет опыта Юнита

### ISSUE THREAD

**Issue by cyrilshishkin** [basiliscos/lua-polkovodets#6]
Я понял ка учитывать опыт Юнита в некоторых конкретных цифровых значениях, но сам коэффициент пока попонятнее.
Опыт влияете в равной мене на защиту и нападение в плане увеличения
Опыт у на от 0 до 50. Причем, хочется нелинейную зависимость разницы в опыте.
То есть в случае 50 и 30, усиление Юнита меньше, чем в случае 20 и 0.

**Comment by basiliscos** [comment]
сделано
